### ISSUE TITLE
Add versioning to all methods

### ISSUE THREAD

**Issue by kevinsmouts** [mattmueller/foursquare2#74]
"As of January 28, 2014, requests that do not include a  v parameter will be rejected."
Source: https://developer.foursquare.com/overview/versioning

```
goza = client.venue('5000659ae4b023056ce815a5')
Foursquare2::APIError: param_error: The Foursquare API no longer supports requests that do not pass in a version parameter. For more details see https://developer.foursquare.com/overview/versioning (410)
```

```
goza = client.venue(:id => '5000659ae4b023056ce815a5', :v => '20140204')
URI::InvalidURIError: bad URI(is not URI?): venues/{:id=>"5000659ae4b023056ce815a5", :v=>"20140204"}
```

**Comment by g3ortega** [comment]
I'm closing this because the client can be initialized with a version, you'll need to add `api_version` param:

`client = Foursquare2::Client.new(:api_version => '20190505')`

I will add later an issue to consider changing to something like VCR to record and test possible changes in the responses depending on the API version provided.
